### ISSUE TITLE
Failed to setup avec la 2.12

### ISSUE THREAD

**Issue by JC38** [TheGui01/Frisquet-connect-for-home-assistant#20]
Bonjour,

Je viens de faire l'upgrade en 2.12 ce matin et l'intégration est ko.
Dans le log, j'ai vu : 
2024-10-10 08:35:17.357 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Maison for frisquet_connect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/__init__.py", line 19, in async_setup_entry
    SiteID = entry.data["SiteID"]
             ~~~~~~~~~~^^^^^^^^^^
KeyError: 'SiteID'

**Comment by TheGui01** [comment]
Bonjour @JC38 ,

As tu supprimé tes devices, redémarré et réinstallé le tout ?

**Comment by JC38** [comment]
Oups, merci du test EagleHD. J'avais pas eu le temps de le faire.

**Comment by TheGui01** [comment]
> Bonjour,
> 
> J'ai le même problème, même en ayant supprimer les devices + restart + add new device

@EagleHD @JC38 
Ok désolé
Je corrige ce soir

**Comment by Al3an** [comment]
Même problème...

**Comment by EagleHD** [comment]
merci @JC38  ;-)

**Comment by Galen-Titanium** [comment]
J'ai rencontré le même problème que beaucoup par contre j'ai supprimé et créé de nouveau et c'est OK. Merci de faire vivre cette intégration elle me rends bien service.

**Comment by TheGui01** [comment]
Hello @JC38 @EagleHD ,

Je viens de push la v2.1.3 qui devrait contourner votre problème 🤞 
Faites moi un retour que je puisse clôturer le ticket 
Merci !

**Comment by JC38** [comment]
J'ai passé un update proposé mais je suis toujours en 2.12 après redémarrage de ha

**Comment by TheGui01** [comment]
@JC38 
Sur la page du device ? J'ai juste oublié de mettre  a jour le numéro de version....
Est ce que ca marche ?

**Comment by EagleHD** [comment]
alors pour ma part, j'ai toujours le problème 

![2024-10-10_21h08_07](https://github.com/user-attachments/assets/67d42c4f-7d2a-407a-a2fa-aa13d1e5ad2b)

**Comment by JC38** [comment]
![image](https://github.com/user-attachments/assets/0bb027a4-b9ea-4818-a211-9dd75b42ee88)

**Comment by TheGui01** [comment]
As tu le log ?

**Comment by EagleHD** [comment]
j'ai supprimé toute l'intégration pour la réinstaller donc j'ai pas accès aux logs, c'est bien ça que tu veux ? le screen shot envoyé c'est quand je veux ajouter l'intégration (demande des identifiants et mot de passe)

**Comment by EagleHD** [comment]
je viens de faire un test en passant par la version 1.8.1 qui fonctionne correctement. Mise à jour en 2.1.3 ça ne fonctionne plus à nouveau. Du coup ci-joint les logs.
![image](https://github.com/user-attachments/assets/aa2f0c17-0bb4-4f11-a6ff-47074810536f)
[home-assistant_frisquet_connect_2024-10-10T19-24-07.085Z.log](https://github.com/user-attachments/files/17333187/home-assistant_frisquet_connect_2024-10-10T19-24-07.085Z.log)

**Comment by TheGui01** [comment]
@EagleHD depuis la 1.8.1 tu peux stp acticer les logs 5 mins et me l'envoyer ensuite en prenant soin de virer tes identifiants et mdp stp ?

**Comment by EagleHD** [comment]
c'est en cours... désolé je débute, mais en ouvrant le fichier log je ne trouve pas mes identifiants (je viens de les changer au cas ou)

**Comment by EagleHD** [comment]
[home-assistant_frisquet_connect_2024-10-10T19-55-53.420Z.log](https://github.com/user-attachments/files/17333610/home-assistant_frisquet_connect_2024-10-10T19-55-53.420Z.log)
j'ai trouvé, ça devrait être mieux là

**Comment by TheGui01** [comment]
Ok je pense avoir compris... donnez moi un peu de temps je serai pas mal occupé ces prochaines semaines.

**Comment by JC38** [comment]
Bonjour,

Voici un log de la "2.13". S'il faut faire un rollback, je ne connais pas la méthode pour le faire juste sur une intégration. Quelqu'un la connait ?

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 8:35:45 AM (1 occurrences)
Last logged: 8:35:45 AM

Error setting up entry Maison for frisquet_connect
Traceback (most recent call last):
  File "/config/custom_components/frisquet_connect/frisquetAPI.py", line 177, in getTokenAndInfo
    self.data[data["sites"][site]]["zone1"]["energy"] = {}
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'zone1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/__init__.py", line 24, in async_setup_entry
    await my_api.getTokenAndInfo(data["zone1"],0,SiteID)
  File "/config/custom_components/frisquet_connect/frisquetAPI.py", line 202, in getTokenAndInfo
    _LOGGER.debug("In PoolFrisquestAPI No zones found in responses :'%s",self.data[data["sites"][site]][idx])
                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 0

**Comment by TheGui01** [comment]
Pour le rollback, sous HACS, tu cliques en haut a droite quand tu es sur
Frisquet puis retelecharger et la tu peux choisir ta version.

**Comment by Al3an** [comment]
MAJ ce matin. 2.12 fonctionne.

**Comment by TheGui01** [comment]
Bonjour @JC38 @EagleHD ,
J'ai publié la release beta 2.1.4. Il y a une toute petite chance qu'elle résolve le problème..
J'ai nettoyé les logs et je n'expose plus les login et pass.
Si ca plante toujours pourrez-vous activer les logs plus de 5min et me les envoyer ici ?
Avec ca je pourrai reproduire votre comportement a l'identique et on devrait avancer ;)

Merci,
Guillaume

**Comment by JC38** [comment]
Bonjour Guillaume

Avec la 2.14, l'intégration elle-même ne remonte pas en erreur dans l'onglet des intégrations mais ses entités sont h.s
Voici le log
2024-10-12 11:53:08.442 ERROR (MainThread) [homeassistant.components.climate] Error while setting up frisquet_connect platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/frisquet_connect/climate.py", line 54, in async_setup_entry
    entity = FrisquetConnectEntity(entry,coordinator.my_api,"zone1",coordinator.my_api.data["nomInstall"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/climate.py", line 117, in __init__
    self._attr_unique_id = str(self.data[site][idx] ["identifiant_chaudiere"]) + str(self.data[site][idx] ["numero"])
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'identifiant_chaudiere'
2024-10-12 11:53:08.444 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up frisquet_connect platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/frisquet_connect/sensor.py", line 34, in async_setup_entry
    if "energy" in coordinator.my_api.data[coordinator.my_api.data["nomInstall"]]["zone1"].keys() :
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'zone1'
2024-10-12 11:53:08.475 ERROR (MainThread) [homeassistant.components.water_heater] Error while setting up frisquet_connect platform for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/frisquet_connect/water_heater.py", line 30, in async_setup_entry
    entity = FrisquetWaterHeater(entry,coordinator.my_api,"MODE_ECS")##.data[site]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/water_heater.py", line 57, in __init__
    self.IDchaudiere =coordinator.data[self.site]["zone1"]["identifiant_chaudiere"]
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'zone1'

**Comment by TheGui01** [comment]
@JC38 
J'ai besoin de plus de log. de ce qui se passe en amont.
Cdt

**Comment by JC38** [comment]
Bonjour,

ça commence mal après le delete des entités, la suppression de l'intégration et se réinstallation, ça plante direct à l'identification.
En attendant, j'ai trouvé ces morceaux de log :
 File "/config/custom_components/frisquet_connect/config_flow.py", line 42, in async_step_user
    return await self.async_step_2()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/config_flow.py", line 72, in async_step_2
    await self.async_set_unique_id(str(self.datadict[site]["zone1"]["identifiant_chaudiere"]))
                                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'zone1'

**Comment by JC38** [comment]
Après une re-re-installation de la beta et toujours le pb de l'authentification, je suis revenu en 1.9.3, l'authentification est passée directe.

**Comment by JC38** [comment]
Je vais recommencer mais il me semble que j'ai eu le message directement après l'ajout de l'intégration sans avoir encore vu cet écran.

**Comment by TheGui01** [comment]
Non c'est pas possible

**Comment by JC38** [comment]
Alors on ne fait pas de la même manière ou on ne parle pas de la même chose.
1. Suppression de l'entité
2. Hacs, redownload , version beta, donwload, reboot obligatoire
3. Après reboot, pas de Frisquet dans écran intégration, obliger de cliquer sur add Integration
4. Add integration, chercher Frisquet, cliquer sur Frisquet Connect, fenêtre de login email/password. Pas vu d'endroit pour activer le log spécifique à l'intégration

**Comment by JC38** [comment]
J'ai une intégration Log Viewer qui logue ce que se passe, voici ce qu'elle logue quand je tent mon authentification :
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/config_flow.py", line 72, in async_step_2
    await self.async_set_unique_id(str(self.datadict[site]["zone1"]["identifiant_chaudiere"]))
                                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'zone1'

**Comment by TheGui01** [comment]
J'ai bien compris ca ca fait plusieurs fois que tu me le dit..
J'ai besoin de comprendre ce qui se passe avant !!
Stp postes tous tes logs

**Comment by JC38** [comment]
Désolé de me répéter mais quand j'ai l'impression que je ne suis pas compris, je recommence.
Voici l'extrait du log posterieur à 20h59, heure du dernier essai
Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:448
First occurred: 8:50:12 PM (2 occurrences)
Last logged: 8:59:34 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 370, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 417, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/config_flow.py", line 42, in async_step_user
    return await self.async_step_2()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/config_flow.py", line 72, in async_step_2
    await self.async_set_unique_id(str(self.datadict[site]["zone1"]["identifiant_chaudiere"]))
                                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'zone1'

**Comment by TheGui01** [comment]
corrigé dans la v2.1.5

**Comment by EagleHD** [comment]
Bonjour TheGui01, 
Désolé j'étais absent, j'ai pas pu te répondre. Néanmoins je voulais te dire que j'ai fait la mise à jour en 2.1.5 et que ça fonctionne, pas d'erreur à la connexion.
Merci à toi !
Bonne journée.
