### ISSUE TITLE
Data frozen

### ISSUE THREAD

**Issue by Amapem** [TheGui01/Frisquet-connect-for-home-assistant#3]
Depuis ce matin 3h les données de frisquet connect ne remontent plus dans HA

![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/59937802/b57b65a9-dbe5-4013-aecb-0ba68523def4)

Log: 👍 

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:898
First occurred: 03:31:49 (66 occurrences)
Last logged: 08:56:48

Update for climate.maison_ledru_rollin_zone_maison fails
Traceback (most recent call last):
  File "/config/custom_components/frisquet_connect/climate.py", line 79, in async_update
    self.data[self.idx] = await FrisquetGetInfo.getTokenAndInfo(self,self.data[self.idx],self.idx)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/frisquetAPI.py", line 55, in getTokenAndInfo
    for i in range(len(response["zones"])):
                       ~~~~~~~~^^^^^^^^^
KeyError: 'zones'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 898, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1216, in async_device_update
    await self.async_update()
  File "/config/custom_components/frisquet_connect/climate.py", line 81, in async_update
    self.data[self.idx]["date_derniere_remontee"] = 0
    ~~~~~~~~~^^^^^^^^^^
KeyError: 'zone1'
```

Je n'ai pas encore relancé HA pour voir si besoin de faire plus de tests.

**Comment by Amapem** [comment]
Oui version 1.6.7

Le debug est déjà activé.
Où se trouve le fichier de logs ?

**Comment by TheGui01** [comment]
Normalement quand tu arretes le debug, ca te télécharge directement le
fichier

**Comment by Amapem** [comment]
Voici le contenu du fichier de log : la même chose...

```
2024-01-19 10:51:48.775 DEBUG (MainThread) [custom_components.frisquet_connect.climate] In Climate.py async update <entity climate.maison_ledru_rollin_zone_maison=auto>
2024-01-19 10:51:48.776 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.maison_ledru_rollin_zone_maison fails
Traceback (most recent call last):
  File "/config/custom_components/frisquet_connect/climate.py", line 79, in async_update
    self.data[self.idx] = await FrisquetGetInfo.getTokenAndInfo(self,self.data[self.idx],self.idx)
                                                                     ~~~~~~~~~^^^^^^^^^^
KeyError: 'zone1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 898, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1216, in async_device_update
    await self.async_update()
  File "/config/custom_components/frisquet_connect/climate.py", line 81, in async_update
    self.data[self.idx]["date_derniere_remontee"] = 0
    ~~~~~~~~~^^^^^^^^^^
KeyError: 'zone1'
2024-01-19 10:51:50.037 DEBUG (MainThread) [custom_components.frisquet_connect.sensor] In sensor.py async update <entity sensor.maison_ledru_rollin_temperature_zone_maison=18.3>
2024-01-19 10:51:50.037 DEBUG (MainThread) [custom_components.frisquet_connect.sensor] In sensor.py async update Climeentitytemp 18.3
2024-01-19 10:51:50.037 DEBUG (MainThread) [custom_components.frisquet_connect.water_heater] In sensor.py async update <entity water_heater.chauffe_eau=Eco + Timer>
2024-01-19 10:51:50.038 DEBUG (MainThread) [custom_components.frisquet_connect.water_heater] In watter heater.py async update water heater
```

**Comment by TheGui01** [comment]
Ok merci !
J'espérais peut etre avoir un peu plus d'info.
J'ai mon idée sur la chose, mais il me faut internet a la maison...
Je te tiens au courant dès que je pousse une update.

**Comment by Amapem** [comment]
As tu du nouveau ?
Ça plante toujours, deux fois aujourd'hui...

**Comment by TheGui01** [comment]
Je n'ai toujours pas internet...
Je n'arrive pas a lancer mon environment de dev en 4G (mediocre)
J'espère retrouver le monde semaine prochaine..
 Un vrai cauchemar, désolé !

**Comment by icna99a** [comment]
même soucis de mon côté...gèle des données.

Bon courage pour récupérer internet.

**Comment by TheGui01** [comment]
Bonjour @Amapem @icna99a ,
Après 1 heure en 4G j'ai réussi a lancer mon environnement de dev...
Je viens de push une release beta : v1.6.7.1
Je ne peux pas la tester car mon HA n'a pas le net.
Pouvez-vous essayer et me faire un retour ?
J'ai peu de recul mais grosso modo, ma compréhension du problème est que ponctuellement les serveurs Frisquet ne retournent pas la réponse attendue et cela casse tout! J'essaie de mieux appréhender cela dans cette  beta

Merci !
Cdt,
Guillaume

**Comment by Amapem** [comment]
Je viens de faire la mise à jour
A suivre

**Comment by Amapem** [comment]
Nouveau gel des données

```
2024-01-31 22:26:07.664 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.maison_ledru_rollin_zone_maison fails
Traceback (most recent call last):
  File "/config/custom_components/frisquet_connect/frisquetAPI.py", line 56, in getTokenAndInfo
    for i in range(len(response["zones"])):
                       ~~~~~~~~^^^^^^^^^
KeyError: 'zones'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/frisquet_connect/climate.py", line 79, in async_update
    self.data[self.idx] = await FrisquetGetInfo.getTokenAndInfo(self,self.data[self.idx],self.idx)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/frisquetAPI.py", line 84, in getTokenAndInfo
    self.data[idx]["date_derniere_remontee"] = 0
    ~~~~~~~~~^^^^^
KeyError: 'zone1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 898, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1216, in async_device_update
    await self.async_update()
  File "/config/custom_components/frisquet_connect/climate.py", line 81, in async_update
    self.data[self.idx]["date_derniere_remontee"] = 0
    ~~~~~~~~~^^^^^^^^^^
KeyError: 'zone1'
2024-01-31 22:26:07.669 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2024-01-31 22:26:07.669 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector
```

**Comment by TheGui01** [comment]
@Amapem @icna99a 
Je viens de push une autre version 1.6.7.2

**Comment by Amapem** [comment]
Cette fois ça ne fonctionne plus : 
![image](https://github.com/TheGui01/Frisquet-connect-for-home-assistant/assets/59937802/635fec24-1933-4d26-b7f2-4fe06d69e52d)

```
2024-02-01 10:55:12.044 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Maison Ledru-Rollin for frisquet_connect
Traceback (most recent call last):
  File "/config/custom_components/frisquet_connect/frisquetAPI.py", line 83, in getTokenAndInfo
    else: self.data[idx]["date_derniere_remontee"] = 0
          ~~~~~~~~~^^^^^
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/__init__.py", line 19, in async_setup_entry
    await my_api.getTokenAndInfo(entry.data["zone1"],0)
  File "/config/custom_components/frisquet_connect/frisquetAPI.py", line 86, in getTokenAndInfo
    self.data[idx]["date_derniere_remontee"] = 0
    ~~~~~~~~~^^^^^
KeyError: 0
2024-02-01 10:55:12.048 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2024-02-01 10:55:12.049 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector
2024-02-01 10:55:12.236 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ludo.lesur@gmail.com for suez_water: None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/suez_water/__init__.py", line 36, in async_setup_entry
    ] = await hass.async_add_executor_job(get_client)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/suez_water/__init__.py", line 29, in get_client
    raise ConfigEntryError
homeassistant.exceptions.ConfigEntryError: None
```

**Comment by TheGui01** [comment]
@Amapem 
Désolé je suis complement a l'aveugle car je ne paux pas lancer l'app chez moi;
Voici une nouvelle version 1.6.7.3 si tu  peux ressayer...
merci

**Comment by Amapem** [comment]
C'est bon 1.6.7.3 installée et fonctionnelle

**Comment by Amapem** [comment]
```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:898
First occurred: 11:26:18 (7 occurrences)
Last logged: 11:56:17

Update for climate.maison_ledru_rollin_zone_maison fails
Traceback (most recent call last):
  File "/config/custom_components/frisquet_connect/frisquetAPI.py", line 84, in getTokenAndInfo
    self.data[idx]["date_derniere_remontee"] = 0
    ~~~~~~~~~^^^^^
KeyError: 'zone1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/frisquet_connect/climate.py", line 79, in async_update
    self.data[self.idx] = await FrisquetGetInfo.getTokenAndInfo(self,self.data[self.idx],self.idx)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/frisquetAPI.py", line 87, in getTokenAndInfo
    self.data[idx]["date_derniere_remontee"] = 0
    ~~~~~~~~~^^^^^
KeyError: 'zone1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 898, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1216, in async_device_update
    await self.async_update()
  File "/config/custom_components/frisquet_connect/climate.py", line 81, in async_update
    self.data[self.idx]["date_derniere_remontee"] = 0
    ~~~~~~~~~^^^^^^^^^^
KeyError: 'zone1'
```

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 11:39:11 (3 occurrences)
Last logged: 11:40:24

[139992931869632] 'zone1'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 731, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/frisquet_connect/climate.py", line 196, in async_set_temperature
    _key = "CONS_CONF_Z"+str(self.data[self.idx]["numero"])
                             ~~~~~~~~~^^^^^^^^^^
KeyError: 'zone1'
```

**Comment by TheGui01** [comment]
@Amapem  dernière tentative avec la 1.6.7.4
Sinon faudra patienter encore que Free me depanne 😮‍💨

**Comment by Amapem** [comment]
mêmes erreurs avec 1.6.7.4
Merci pour la réactivité

**Comment by icna99a** [comment]
J'ai installé la 1.6.7.4 aussi....à suivre !

**Comment by icna99a** [comment]
Pareil ici, c'est re-figé.

**Comment by TheGui01** [comment]
@Amapem  @icna99a 
J'ai trouvé un stupidité dans ce que j'avais fait. Ca pourrait etre mieux avec la v1.6.7.5...
Sinon j'espère avoir un technicien Free semaine prochaine

**Comment by icna99a** [comment]
instalée !!

**Comment by icna99a** [comment]
ça reste globalement figé même si de temps en temps il semblerait que des infos remontent.

**Comment by TheGui01** [comment]
Hello @icna99a 
Désolé mais ca va pas trop m'aider!
A noter que l'app effectue des requete aux serveur Frisquet toutes les 5 minutes.
Localement, votre chaudière peut aussi ajouter un décalage.
Grosso modo à +ou- 5 minutes on doit avoir la même chose que sur l'app Frisquet Connect.
Un technicien passe lundi matin me remettre la fibre donc sauf catastrophe, je pourrai monitorer le comportement de l'app sous HA mercredi. Puis publier un vrai correctif. 
Laissez donc moi 1 semaine et j'ai bon espoir de vous livrer qqch de correct

Bon week end

**Comment by icna99a** [comment]
Bien noté mais là je pense que c'est figé pour de bon.

Merci beaucoup pour le boulot que tu fais et je croise les doigts pour ta fibre !!!

**Comment by TheGui01** [comment]
Bonjour @Amapem @icna99a 
Je viens de publier un fix que j'ai pu testé.
n'hésitez pas a revenir vers moi si ca ne va pas.

**Comment by icna99a** [comment]
je viens de rentrer, j'installe ça !!! merci

**Comment by TheGui01** [comment]
> je viens de rentrer, j'installe ça !!! merci

Attendd ya un nouveau bug... je corrige ce soir...

**Comment by TheGui01** [comment]
> > je viens de rentrer, j'installe ça !!! merci
> 
> Attendd ya un nouveau bug... je corrige ce soir...

En fait c'est tout bon.
C'est le module Frisquet chez moi qui avait besoin d'un reboot !
