### ISSUE TITLE
Erreur depuis 28/11/2024 23h

### ISSUE THREAD

**Issue by pafnow** [TheGui01/Frisquet-connect-for-home-assistant#30]
Bonjour,

J'ai à nouveau un bug avec Frisquet Connect depuis hier soir 23h environ.
Cette fois-ci, l'application semble fonctionner correctement, l'intégration non.

Dans les logs de HA j'ai ceci

```
2024-11-29 09:26:54.835 WARNING (MainThread) [py.warnings] /usr/src/homeassistant/homeassistant/helpers/entity.py:1351: RuntimeWarning: coroutine 'FrisquetGetInfo.async_add_listener' was never awaited
  self._on_remove.pop()()
2024-11-29 09:27:15.767 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.frisquet_connect_consomation_chauffage fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 944, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/frisquet_connect/sensor.py", line 129, in async_update
    self._attr_native_value = self.coordinator.data[self.site][self.idx]["energy"]["CHF"]
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'energy'
2024-11-29 09:27:15.769 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.frisquet_connect_consomation_eau_chaude fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 944, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/frisquet_connect/sensor.py", line 65, in async_update
    self._attr_native_value = self.coordinator.data[self.site][self.idx]["energy"]["SAN"]
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'energy'
2024-11-29 09:27:15.772 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.frisquet_connect_temperature_zone_1 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 944, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/frisquet_connect/sensor.py", line 321, in async_update
    self.coordinator.data[self.site][self.idx]["TAMB"] / 10)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'TAMB'
2024-11-29 09:27:15.780 ERROR (MainThread) [homeassistant.helpers.entity] Update for water_heater.chauffe_eau fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 944, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/frisquet_connect/water_heater.py", line 53, in async_update
    self.token = self.coordinator.data[self.site]["zone1"]["token"]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'token'
```

Suis-je le seul dans ce cas ? Une idée d'où ça peut venir ?
Merci encore et bonne journée

**Comment by TheGui01** [comment]
@pafnow non aucune idée tout fonctionne chez moi.
Un reboot HA ne solutionne pas ?

**Comment by pafnow** [comment]
Shame on me !
En effet un reboot de HA a solutionné le problème ...
Désolé du dérangement.

En y réfléchissant un peu plus, j'ai l'impression que ça a buggué à un moment où j'ai ouvert/utilisé l'appli officielle Frisquet, je verrais si ca ce reproduit.

Bonne journée
