### ISSUE TITLE
problème au moment d'entre le login/passwd

### ISSUE THREAD

**Issue by defaliz** [TheGui01/Frisquet-connect-for-home-assistant#9]
Installation parfaite sur HA dernière version
au moment de l'intégration je saisis mes identifiants
et une erreur s'affiche : "Unknown error occurred"
voici les logs de HA :
2024-03-02 15:12:22.835 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 185, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 358, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 404, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 501, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/config_flow.py", line 41, in async_step_user
    self.datadict :dict = data["zone1"]
                          ~~~~^^^^^^^^^^
KeyError: 'zone1'

**Comment by TheGui01** [comment]
Bonjour @defaliz 
Je pense que la reponse de l'API pour une PAC est différente.
J'ai besoin que vous mettiez l'integration en mode debug de la facon suivante :
Dans votre fichier configuration.yaml il faut mettre : 
logger:
    default: info
    logs:
        custom_components.frisquet_connect: debug

Ensuite refaire le processus de connexion qvec votre email et mdp. Vous devriez alors avopir, dans votre journal de log une longue ligne du type 👍 
) [custom_components.frisquet_connect.frisquetAPI] In PoolFrisquestAPI response 

Pouvez-vous m'ajouter le contenu de cette ligne ici en prenant soin de ne pas me transmettre vos ID et mot de passe

Merci

**Comment by defaliz** [comment]
voila, j'ai remplacé les infos sensibles par des X, en tout cas les bonnes infos sont remontées, donc pas de souci au niveau de la connexion... merci pour ce développement, ça fait longtemps que j'attends ce type d'intégration !
 
2024-03-02 15:42:11.722 DEBUG (MainThread) [custom_components.frisquet_connect.config_flow] _user_input={'email': 'xxxxxx', 'password': 'xxxxxxx'}
2024-03-02 15:42:11.722 DEBUG (MainThread) [custom_components.frisquet_connect.frisquetAPI] In getToken and info Frisquet API
2024-03-02 15:42:12.512 DEBUG (MainThread) [custom_components.frisquet_connect.frisquetAPI] In PoolFrisquestAPI with url :'https://fcutappli.frisquet.com/api/v1/sites/xxxxxxx?token=xxxxxxxxxx
2024-03-02 15:42:12.645 DEBUG (MainThread) [custom_components.frisquet_connect.frisquetAPI] In PoolFrisquestAPI response :'{'sigmacom': 'xxxxxxx', 'produit': {'gamme': None, 'chaudiere': None, 'version1': None, 'version2': None, 'puissance': None}, 'agi': 'F7AC00000', 'id_equipement': 2, 'identifiant_chaudiere': 'xxxxxxx', 'nom': 'Maison', 'code_postal': 'xxxxx', 'code_pays': 'FR', 'emails_alerte': ['xxxxxxx'], 'telephones_alerte': [], 'date_derniere_remontee': 'xxxxxx', 'timezone': 'Europe/Paris', 'carac_site': {'DATE_HEURE_CHAUDIERE': '1709390532', 'CHAUDIERE_EN_VEILLE': False, 'AUTO_MANU': True}, 'ecs': {'TYPE_ECS': None, 'solaire': False, 'AVEC_ECS': None, 'MODE_ECS': None, 'MODE_ECS_SOLAIRE': None, 'MODE_ECS_PAC': {'nom': 'Stop', 'id': 0}}, 'environnement': {'T_EXT': 82, 'T_EXT_GE': None}, 'vacances': {'DATE_DEP_VACANCES': None, 'DATE_RET_VACANCES': None, 'MODE_VACANCES': False}, 'zones': [{'boost_disponible': True, 'id': 65309, 'identifiant': 'Z1', 'numero': 1, 'nom': 'Zone 1', 'carac_zone': {'MODE': 6, 'SELECTEUR': 6, 'TAMB': 120, 'CAMB': 120, 'DERO': False, 'CONS_RED': 120, 'CONS_CONF': 120, 'CONS_HG': 80, 'ACTIVITE_BOOST': False}, 'programmation':

**Comment by defaliz** [comment]
ensuite après le paquet de données commencent les erreurs proprement dites :

 {'nom': 'Eco', 'id': 3}, {'nom': 'Stop', 'id': 0}], 'alarmes': [], 'alarmes_pro': []}
2024-03-02 15:42:12.647 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by TheGui01** [comment]
Pouvez vous tout envoyer ? J'avoue ne pas comprendre.
Sous quelle version de HA êtes vous ?

**Comment by defaliz** [comment]
OS Version:               Home Assistant OS 12.0
  Home Assistant Core:      2024.2.4

**Comment by defaliz** [comment]
voici l'intégralité des logs, dans les données on voit passer nom': 'Zone 1' or à la fin du log on lit "zone1"

[custom_components.frisquet_connect.config_flow] config_flow step user (1). 1er appel : pas de user_input -> on affiche le form user_form
2024-03-02 15:42:11.722 DEBUG (MainThread) [custom_components.frisquet_connect.config_flow] _user_input={'email': 'xxxxxxx', 'password': 'xxxxxxxx'}
2024-03-02 15:42:11.722 DEBUG (MainThread) [custom_components.frisquet_connect.frisquetAPI] In getToken and info Frisquet API
2024-03-02 15:42:12.512 DEBUG (MainThread) [custom_components.frisquet_connect.frisquetAPI] In PoolFrisquestAPI with url :'https://fcutappli.frisquet.com/api/v1/sites/xxxxx?token=xxxxx
2024-03-02 15:42:12.645 DEBUG (MainThread) [custom_components.frisquet_connect.frisquetAPI] In PoolFrisquestAPI response :'{'sigmacom': 'xxxxxxxxx', 'produit': {'gamme': None, 'chaudiere': None, 'version1': None, 'version2': None, 'puissance': None}, 'agi': 'xxxxxx', 'id_equipement': 2, 'identifiant_chaudiere': 'xxxxx', 'nom': 'Maison', 'code_postal': 'xxxxx', 'code_pays': 'FR', 'emails_alerte': ['xxxx'], 'telephones_alerte': [], 'date_derniere_remontee': 'xxxxx', 'timezone': 'Europe/Paris', 'carac_site': {'DATE_HEURE_CHAUDIERE': 'xxxxx', 'CHAUDIERE_EN_VEILLE': False, 'AUTO_MANU': True}, 'ecs': {'TYPE_ECS': None, 'solaire': False, 'AVEC_ECS': None, 'MODE_ECS': None, 'MODE_ECS_SOLAIRE': None, 'MODE_ECS_PAC': {'nom': 'Stop', 'id': 0}}, 'environnement': {'T_EXT': 82, 'T_EXT_GE': None}, 'vacances': {'DATE_DEP_VACANCES': None, 'DATE_RET_VACANCES': None, 'MODE_VACANCES': False}, 'zones': [{'boost_disponible': True, 'id': 65309, 'identifiant': 'Z1', 'numero': 1, 'nom': 'Zone 1', 'carac_zone': {'MODE': 6, 'SELECTEUR': 6, 'TAMB': 120, 'CAMB': 120, 'DERO': False, 'CONS_RED': 120, 'CONS_CONF': 120, 'CONS_HG': 80, 'ACTIVITE_BOOST': False}, 'programmation': [{'jour': 0, 'plages': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]}, {'jour': 1, 'plages': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]}, {'jour': 2, 'plages': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]}, {'jour': 3, 'plages': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]}, {'jour': 4, 'plages': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]}, {'jour': 5, 'plages': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]}, {'jour': 6, 'plages': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]}]}], 'modes_ecs': [{'nom': 'MAX', 'id': 7}, {'nom': 'Eco', 'id': 3}, {'nom': 'Stop', 'id': 0}], 'alarmes': [], 'alarmes_pro': []}
2024-03-02 15:42:12.647 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 185, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 358, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 404, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 501, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/config_flow.py", line 41, in async_step_user
    self.datadict :dict = data["zone1"]
                          ~~~~^^^^^^^^^
KeyError: 'zone1'

**Comment by TheGui01** [comment]
@defaliz 
J'ai modifié le code des fichier config_flow.py et  FrisquetAPI.py pour avoir des logs supplémentaires.
Est ce que tu arrive a mettre a jour les 2 fichiers manuellement( je n'ai pas créé de relrease.) ?

Ceci devrait me permettre d'avoir des logs en plus, juste avant l'erreur et de mieux comprendre

**Comment by defaliz** [comment]
merci, j'apprécie l'effort...
voici les logs, j'ai coupé les données pour ne pas avoir a remasquer les données perso... mais si tu veux je remets tout (mais ça ne change pas...)
on voit bien une erreur python --> TypeError
si tu veux je peux tester directement les scripts en ligne de commande...

'CONS_HG': 80, 'ACTIVITE_BOOST': False}, 'programmation': [{'jour': 0, 'plages': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]}, {'jour': 1, 'plages': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]}, {'jour': 2, 'plages': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]}, {'jour': 3, 'plages': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]}, {'jour': 4, 'plages': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]}, {'jour': 5, 'plages': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]}, {'jour': 6, 'plages': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]}]}], 'modes_ecs': [{'nom': 'MAX', 'id': 7}, {'nom': 'Eco', 'id': 3}, {'nom': 'Stop', 'id': 0}], 'alarmes': [], 'alarmes_pro': []}
2024-03-02 18:22:13.231 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/config/custom_components/frisquet_connect/frisquetAPI.py", line 70, in getTokenAndInfo
    self.data["zone"+str(i+1)]["produit"]=  response["produit"]["chaudiere"]+" "+response["produit"]["gamme"]+" " +response["produit"]["puissance"]
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 185, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 358, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 404, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 501, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/config_flow.py", line 40, in async_step_user
    data = await FrisquetGetInfo.getTokenAndInfo(self,data,0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frisquet_connect/frisquetAPI.py", line 101, in getTokenAndInfo
    _LOGGER.debug("In PoolFrisquestAPI No zones found in responses :'%s",self.data[idx])
                                                                         ~~~~~~~~~^^^^^
KeyError: 0

**Comment by defaliz** [comment]
sinon c'est peut-être sur l'id de la chaudiére, plus de caractères que les autres modèles ? sur qui aurait une incidence sur la mise en forme des données... j'écris ce qui me vient à l'esprit...

**Comment by TheGui01** [comment]
@defaliz 
Le probleme est par ici :
self.data["zone"+str(i+1)]["produit"]= response["produit"]["chaudiere"]+" "+response["produit"]["gamme"]+" " +response["produit"]["puissance"]
Je vais chercher des éléments qui n'existent pas sur une PAC
Je te propose un fix ce soir ou demain

**Comment by defaliz** [comment]
un grand merci ! veux-tu la ref de ma PAC c'est une teamao, as-tu besoin du modèle ?
bonne soirée

**Comment by TheGui01** [comment]
@defaliz 
Normalement je récupère les références du produit dans la reponse mais la j'ai rien qui remonte chez toi...
Aussi, je vois une température de consigne et une température mesurée de 12°C
Tu confirmes ?

**Comment by TheGui01** [comment]
@defaliz 
Je viens de publier une version 2.8.0 peux tu tester ?
Si c'est ok je te conseillles de retirer les log debug mis dans configuation.yaml car ca va charger tes logs

**Comment by defaliz** [comment]
j'ai donwloadé le git et fait un git clone dans custom-components
ça suffit ?

**Comment by defaliz** [comment]
En fait j'ai retéléchargé via HACS et...
ça fonctionne !!!!
t'es trop fort !
un très grand merci et une douce soirée : )
Alain

**Comment by TheGui01** [comment]
@defaliz 
Je pense
Il suffit de refaire ce que tu as fait initialement
Le versionning est intéressant si tu utilises l'integration depuis hacs
